name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync frontend except rating.json
        run: |
          aws s3 sync frontend/ s3://nayadriver.com --delete --exclude "rating.json"

      - name: Upload rating.json with cache control
        run: |
          aws s3 cp frontend/rating.json s3://nayadriver.com/rating.json \
            --cache-control "max-age=604800" \
            --acl public-read \
            --content-type "application/json"
